apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: my-namespace
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: test-cont
        image: sunandgmohan/nodetest
        ports:
          - containerPort: 3000
